In [85]:
import numpy as np
import cv2
from numpy.lib.stride_tricks import sliding_window_view
import os
from distance.tools import l2_distance, l1_distance
import matplotlib.pyplot as plt
import random

In [103]:
left_image_path = "./data/Tsukuba/left.png"
right_image_path = "./data/Tsukuba/right.png"

left_img = cv2.imread(left_image_path, 0)
right_img = cv2.imread(right_image_path, 0)

left_img = left_img.astype(np.float32)
right_img = right_img.astype(np.float32)

#cv2.imshow("left image", left_img)

In [107]:
img = cv2.imread("./data/results/vectorization_l2_55.png", 0)
img = img.astype(np.float32)
img

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., 10., 20., ..., 10.,  0.,  0.],
       [ 0., 10., 20., ..., 10.,  0.,  0.],
       ...,
       [ 0., 10., 20., ...,  0.,  0.,  0.],
       [ 0., 10., 20., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [104]:
disparity_range = 16
distance = "l2"
scale = 10
save_result = True
results_path = "./data/results"
id = random.randint(0, 100)
kernel_size = (3,3)

In [106]:
id

95

In [105]:
height, width = left_img.shape

costs = np.full((height, width, disparity_range), fill_value = 255, dtype = np.float32)
half_kernel = int((kernel_size[0] - 1) / 2)

for j in range(disparity_range):
    left_d = left_img[half_kernel: height - half_kernel, half_kernel + j: width - half_kernel]
    right_d = right_img[:, 0: width - j]
    h,w = left_d.shape

    v_right = sliding_window_view(right_d, (3,3))
    
    right_cumsum = np.array([np.cumsum(i)[-1] for l in v_right for i in l])
    right_cumsum_rs = right_cumsum.reshape(h, w)

    if distance == "l1":
        costs[half_kernel: height - half_kernel, half_kernel + j: width - half_kernel, j] = l1_distance(left_d, right_cumsum_rs)
        
    if distance == "l2":
        costs[half_kernel: height - half_kernel, half_kernel + j: width - half_kernel, j] = l2_distance(left_d, right_cumsum_rs)

    min_cost_indices = np.argmin(costs, axis = 2)
    depth = min_cost_indices * scale
    depth = depth.astype(np.uint8)

if save_result == True:
    print("Saving result...")
    cv2.imwrite(f"{results_path}/vectorization_{distance}_{id}.png", depth)
    cv2.imwrite(f"{results_path}/vectorization_{distance}_{id}_color.png", cv2.applyColorMap(depth, cv2.COLORMAP_JET))
print("Done!")

 

Saving result...
Done!


(288, 384)

In [14]:
padding = 10 

c2 = np.full((height + 10, width + 10), fill_value = 255, dtype=np.float32)

center = padding // 2
c2[center: center + height, 
   center: center + width] = left_img

In [95]:
x = np.arange(25)
x = x.reshape((5,5))
x_slide = sliding_window_view(x, (3,3))
x_slide.shape

(3, 3, 3, 3)

In [96]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
x2 = np.array(list(np.cumsum(i)[-1] for l in x_slide for i in l))
x2 = x2.reshape((3,3))
x2

array([[ 54,  63,  72],
       [ 99, 108, 117],
       [144, 153, 162]])

In [16]:
right_img.shape

(288, 384)

In [17]:


window = (5,5)

v_right = sliding_window_view(right_img, window)


In [13]:
# window size(3,3)
v_right.shape

(286, 382, 3, 3)

In [24]:
disparity = 4
left_d = left_img[1: height - 1, 1 + 4: width - 1]
right_d = right_img[:, 0:width - 4]

v_right = sliding_window_view(right_d, (3,3))
print("left shape", left_d.shape)
print("right shape", v_right.shape)

left shape (286, 378)
right shape (286, 378, 3, 3)


In [83]:
value = np.full((height, width), fill_value = 255, dtype=np.float32)

In [84]:
right_cumsum = np.array([np.cumsum(i)[-1] for l in v_right for i in l])
right_cumsum_rs = right_cumsum.reshape(286, 378)
value[1: height - 1, 1 + 4: width - 1] = l2_distance(left_d, right_cumsum_rs)

In [ ]:
cv2.imwrite(f"{results_path}/vectorization_{distance}_{id}.png", value)
cv2.imwrite(f"{results_path}/vectorization_{distance}_{id}_color.png", cv2.applyColorMap(value, cv2.COLORMAP_JET))

In [26]:
  if distance == "l2":
#         costs[:, j: width, j] = l2_distance(left_d, right_d)

#     min_cost_indices = np.argmin(costs, axis = 2)
#     depth = min_cost_indices * scale
#     depth = depth.astype(np.uint8)

# if save_result == True:
#     print("Saving result...")
#     cv2.imwrite(f"{results_path}/vectorization_{distance}_{id}.png", depth)
#     cv2.imwrite(f"{results_path}/vectorization_{distance}_{id}_color.png", cv2.applyColorMap(depth, cv2.COLORMAP_JET))


(286, 378)